---
title: "Rap Artists"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages

```{r}
library(tidyverse)
library(ggrepel)
library(emojifont)
library(showtext)
```

# Data

```{r}
polls <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-14/polls.csv')
rankings <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-14/rankings.csv')
```

# Missing values

```{r}
polls %>% 
  summarise(across(.fns = ~sum(is.na(.)))) # 530 NAs in critic_country2

rankings %>% 
  summarise(across(.fns = ~sum(is.na(.)))) # 0 NAs
```

# Creating labels 

```{r}
label_data <- rankings %>% 
  filter(gender == "female") %>% 
  filter(points >= 10) %>% 
  mutate(artist_song = str_glue("{title} - {artist}"))
```

```{r}
font_add_google("ZCOOL KuaiLe", "zcool")
font_add_google("Rubik", "rubik")

library(ggthemr)
ggthemr("dust")
```


# Plotting female rappers

```{r}
rankings %>% 
  filter(gender == "female") %>% 
  ggplot() +
  geom_text(
    aes(
      y = points, 
      x = year,
      label = fontawesome("fa-microphone")),
    colour = "#5C4F41",
    family='fontawesome-webfont'
  ) +
  geom_label_repel(
    aes(
      y = points, 
      x = year, 
      label = artist_song,
      fill = artist_song
    ), 
    data = label_data,
    label.padding = unit(0.2, "lines"), 
    label.size = 0,
    color = "black",
    min.segment.length = 0,
    segment.color = "#5C4F41",
    family = "zcool"
    # arrow = arrow(angle = 30, length = unit(0.1, "inches")),
    # nudge_x = 5,
    # nudge_y = 1
  ) +
  scale_fill_manual(
    values = c(
      "#ccd5ae",
      "#e9edc9",
      "#e6dca5",
      "#faedcd",
      "#d4a373",
      "#c6c98d",
      "#e6d4ba"
    )
  ) +
  labs(
    title = "top songs by female rappers.",
    x = "Year",
    y = "Points"
  ) +
  theme(
    legend.position = "none",
    axis.text = element_text(family = "rubik"),
    plot.title = element_text(family = "rubik", 
                              face = "bold",
                              size = 20,
                              hjust = 1,
                              vjust = 1),
    axis.title = element_text(family = "rubik")
    
  ) +
  coord_fixed(ratio = 1/1.5)


ggsave(filename="plots/female_rappers.png", 
       device="png", 
       height=5, 
       width=8, 
       units="in", 
       dpi=500)

```


